### PR TITLE
Fix path in template and database location attributes

### PR DESCRIPTION
**Pull request by jugatsu**
Fixes https://github.com/grdnrio/windows-security-policy/issues/19

### CODE REVIEW

**Comment by grdnrio** [comment]
Thanks, using a single quote you are correct.

**Comment by grdnrio** [comment]
@jugatsu can you update metadata and CHANGELOG?

**Comment by jugatsu** [comment]
@grdnrio done

**Comment by grdnrio** [comment]
Thanks @jugatsu. I'm finishing of some integration tests for this and will merge after re-running.

**Pull request merged**
